const menuToggle = document.querySelector('.menu-toggle');
const menu = document.querySelector('#nav-menu');
menuToggle?.addEventListener('click', () => { const isOpen = menu.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', isOpen); });
const toast = document.querySelector('#toast');
function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 3200); }
document.querySelectorAll('.finder-item').forEach(item => item.addEventListener('click', () => { document.querySelector('.finder-item.active')?.classList.remove('active'); item.classList.add('active'); }));
document.querySelector('#finder-go')?.addEventListener('click', () => { const selected = document.querySelector('.finder-item.active')?.dataset.service || 'care'; showToast(`Finding trusted ${selected.toLowerCase()} near Nagpur…`); document.querySelector('#nearby-care').scrollIntoView({ behavior: 'smooth' }); });
document.querySelector('#story-button')?.addEventListener('click', () => document.querySelector('#how-it-works').scrollIntoView({ behavior: 'smooth' }));
document.querySelectorAll('.service-card').forEach(card => card.addEventListener('click', event => { event.preventDefault(); const action = card.dataset.serviceAction; if (action === 'scan') return openMedicineScanner(); if (action === 'hospitals') { document.querySelector('#nearby-care').scrollIntoView({ behavior: 'smooth' }); return; } if (action === 'blood') return openBloodCamps(); if (action === 'report') return openReportAnalyzer(); showToast(`${card.querySelector('h3').textContent} will be available in the SCANPHARMA app.`); }));

const providers = { hospital: [{ name: 'AIIMS Nagpur', place: 'MIHAN, Nagpur', note: 'Public tertiary care', icon: '✦', lat: 21.0237, lng: 79.0346 }, { name: 'KIMS–Kingsway Hospitals', place: 'Kingsway Road, Nagpur', note: 'Multi-speciality care', icon: '✚', lat: 21.1511, lng: 79.0832 }, { name: 'Wockhardt Hospitals Nagpur', place: 'Ramdaspeth, Nagpur', note: 'Heart & multi-speciality', icon: '♥', lat: 21.1341, lng: 79.0791 }, { name: 'Alexis Multispeciality Hospital', place: 'Mankapur, Nagpur', note: 'Emergency & diagnostics', icon: '✚', lat: 21.1638, lng: 79.0919 }], pharmacy: [{ name: 'Apollo Pharmacy · Indora', place: 'Ambedkar Road, Nagpur', note: 'Pharmacy · check stock', icon: '✚', lat: 21.1691, lng: 79.0960 }, { name: 'Apollo Pharmacy · Nandanvan', place: 'Nandanvan, Nagpur', note: 'Pharmacy · check stock', icon: '✚', lat: 21.1423, lng: 79.1156 }, { name: 'Apollo Pharmacy · Manewada', place: 'Manewada Road, Nagpur', note: 'Pharmacy · check stock', icon: '✚', lat: 21.1117, lng: 79.1128 }, { name: 'Apollo Pharmacy · Khamla', place: 'Khamla Road, Nagpur', note: 'Pharmacy · check stock', icon: '✚', lat: 21.1139, lng: 79.0715 }], lab: [{ name: 'Dr Lal PathLabs · Medical Square', place: 'HKMC Complex, Nagpur', note: 'Diagnostic centre', icon: '⌁', lat: 21.1298, lng: 79.0993 }, { name: 'Dr Lal PathLabs · Pratap Nagar', place: 'Pratap Nagar, Nagpur', note: 'Diagnostic centre', icon: '⌁', lat: 21.1165, lng: 79.0726 }, { name: 'Metropolis Healthcare', place: 'Nagpur collection centre', note: 'Home collection available', icon: '⌁', lat: 21.1458, lng: 79.0882 }, { name: 'Alexis Hospital Laboratory', place: 'Mankapur, Nagpur', note: 'Hospital diagnostic lab', icon: '⌁', lat: 21.1638, lng: 79.0919 }] };
let activeProviderType = 'hospital'; let selectedProvider = providers.hospital[0]; let userLocation = null;
const providerList = document.querySelector('#provider-list'); const providerMap = document.querySelector('#provider-map'); const mapStatus = document.querySelector('#map-status'); const gpsStatus = document.querySelector('#gps-status'); const routeName = document.querySelector('#route-name'); const routeDetail = document.querySelector('#route-detail'); const directions = document.querySelector('#map-directions');
function distanceKm(a, b) { const r = 6371, rad = value => value * Math.PI / 180, dLat = rad(b.lat - a.lat), dLng = rad(b.lng - a.lng); const x = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLng / 2) ** 2; return r * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }
function renderProviders() { if (!providerList) return; providerList.innerHTML = providers[activeProviderType].map(provider => { const selected = provider.name === selectedProvider.name ? ' active' : ''; const distance = userLocation ? `${distanceKm(userLocation, provider).toFixed(1)} km` : provider.note; return `<button class="provider-card${selected}" type="button" data-provider="${provider.name}"><span class="provider-type-icon provider-${activeProviderType}">${provider.icon}</span><span><h3>${provider.name}</h3><p>${provider.place}</p></span><span class="provider-meta"><b>${distance}</b><small>View route ↗</small></span></button>`; }).join(''); providerList.querySelectorAll('.provider-card').forEach(card => card.addEventListener('click', () => setSelectedProvider(providers[activeProviderType].find(item => item.name === card.dataset.provider)))); }
function setSelectedProvider(provider) { selectedProvider = provider; routeName.textContent = provider.name; const origin = userLocation ? `&origin=${userLocation.lat},${userLocation.lng}` : ''; directions.href = `https://www.google.com/maps/dir/?api=1${origin}&destination=${provider.lat},${provider.lng}`; providerMap.src = `https://www.openstreetmap.org/export/embed.html?bbox=${provider.lng - .018}%2C${provider.lat - .014}%2C${provider.lng + .018}%2C${provider.lat + .014}&layer=mapnik&marker=${provider.lat}%2C${provider.lng}`; if (userLocation) { const distance = distanceKm(userLocation, provider).toFixed(1); mapStatus.textContent = `${distance} km from your GPS location`; gpsStatus.textContent = `Route ready to ${provider.name}`; routeDetail.textContent = `${provider.place} · ${distance} km away`; } else { mapStatus.textContent = 'Showing provider location'; gpsStatus.textContent = 'Enable GPS for route distance'; routeDetail.textContent = `${provider.place} · Tap for directions`; } renderProviders(); }
document.querySelectorAll('.provider-tab').forEach(tab => tab.addEventListener('click', () => { document.querySelector('.provider-tab.active')?.classList.remove('active'); tab.classList.add('active'); activeProviderType = tab.dataset.providerType; setSelectedProvider(providers[activeProviderType][0]); }));
async function getDeviceLocation() { const nativeRuntime = window.Capacitor?.isNativePlatform?.(); if (nativeRuntime && window.SCANPHARMA_GEOLOCATION) { const permission = await window.SCANPHARMA_GEOLOCATION.requestPermissions(); if (permission.location !== 'granted' && permission.coarseLocation !== 'granted') throw new Error('Location permission was not granted'); const position = await window.SCANPHARMA_GEOLOCATION.getCurrentPosition({ enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 }); return { lat: position.coords.latitude, lng: position.coords.longitude }; } if (!navigator.geolocation) throw new Error('GPS is not supported by this browser.'); return new Promise((resolve, reject) => navigator.geolocation.getCurrentPosition(position => resolve({ lat: position.coords.latitude, lng: position.coords.longitude }), reject, { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 })); }
document.querySelector('#use-gps')?.addEventListener('click', async () => { gpsStatus.textContent = 'Requesting your location…'; try { userLocation = await getDeviceLocation(); showToast('GPS location enabled. Distances are now personalised.'); setSelectedProvider(selectedProvider); } catch { gpsStatus.textContent = 'Location access was not granted'; showToast('We need location permission to calculate your route.'); } });
setSelectedProvider(selectedProvider);

const configured = window.SCANPHARMA_SUPABASE_URL && window.SCANPHARMA_SUPABASE_PUBLISHABLE_KEY; const db = configured && window.supabase ? window.supabase.createClient(window.SCANPHARMA_SUPABASE_URL, window.SCANPHARMA_SUPABASE_PUBLISHABLE_KEY) : null;
async function loadProvidersFromDatabase() { if (!db) return; const { data, error } = await db.from('providers').select('provider_type,name,address,service_note,latitude,longitude').eq('city', 'Nagpur'); if (error || !data?.length) return; ['hospital', 'pharmacy', 'lab'].forEach(type => { providers[type] = data.filter(row => row.provider_type === type).map(row => ({ name: row.name, place: row.address, note: row.service_note, icon: type === 'hospital' ? '✦' : type === 'pharmacy' ? '✚' : '⌁', lat: Number(row.latitude), lng: Number(row.longitude) })); }); selectedProvider = providers[activeProviderType][0]; setSelectedProvider(selectedProvider); }
loadProvidersFromDatabase();
const openModal = id => { const modal = document.querySelector(id); modal?.classList.add('open'); modal?.setAttribute('aria-hidden', 'false'); }; const closeModal = modal => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); };
document.querySelector('#open-login')?.addEventListener('click', () => openModal('#login-modal')); document.querySelector('#open-donor')?.addEventListener('click', () => openModal('#donor-modal')); document.querySelectorAll('[data-close-modal]').forEach(button => button.addEventListener('click', () => closeModal(button.closest('.modal')))); document.querySelectorAll('.modal').forEach(modal => modal.addEventListener('click', event => { if (event.target === modal) closeModal(modal); })); document.addEventListener('keydown', event => { if (event.key === 'Escape') document.querySelectorAll('.modal.open').forEach(closeModal); });
document.querySelectorAll('.role-choice').forEach(choice => choice.addEventListener('click', () => { document.querySelector('.role-choice.active')?.classList.remove('active'); choice.classList.add('active'); document.querySelector('#login-form [name="role"]').value = choice.dataset.role; }));
let signUpMode = false; const signUpToggle = document.querySelector('#signup-toggle'); signUpToggle?.addEventListener('click', () => { signUpMode = !signUpMode; document.querySelector('#login-form button[type="submit"]').innerHTML = signUpMode ? 'Create my account <span>→</span>' : 'Log in <span>→</span>'; signUpToggle.textContent = signUpMode ? 'Already have an account? Log in' : 'New here? Create an account'; document.querySelector('#login-status').textContent = ''; });
function formMessage(element, message, error = false) { element.textContent = message; element.classList.toggle('error', error); }
document.querySelector('#login-form')?.addEventListener('submit', async event => { event.preventDefault(); const form = new FormData(event.currentTarget), status = document.querySelector('#login-status'); if (!db) return formMessage(status, 'The secure login service is being connected. Please try again shortly.', true); formMessage(status, signUpMode ? 'Creating your account…' : 'Signing you in…'); const options = { email: form.get('email'), password: form.get('password') }; const result = signUpMode ? await db.auth.signUp({ ...options, options: { data: { role: form.get('role') } } }) : await db.auth.signInWithPassword(options); if (result.error) return formMessage(status, result.error.message, true); formMessage(status, signUpMode ? 'Account created — please check your email to confirm it.' : 'Welcome back. You are now signed in.'); if (!signUpMode) setTimeout(() => closeModal(document.querySelector('#login-modal')), 1000); });
document.querySelector('#donor-form')?.addEventListener('submit', async event => { event.preventDefault(); const status = document.querySelector('#donor-status'); if (!db) return formMessage(status, 'The secure donor registry is being connected. Please try again shortly.', true); const { data: { user } } = await db.auth.getUser(); if (!user) { formMessage(status, 'Please log in or create an account before saving your pledge.', true); return; } const form = new FormData(event.currentTarget); formMessage(status, 'Saving your private pledge…'); const { error } = await db.from('organ_donor_pledges').insert({ user_id: user.id, full_name: form.get('full_name'), phone: form.get('phone'), email: form.get('email'), donation_interest: form.get('donation_interest'), consent: form.get('consent') === 'on' }); if (error) return formMessage(status, error.message, true); formMessage(status, 'Your pledge has been saved privately. Thank you for your generosity.'); event.currentTarget.reset(); });

const medicineScannerModal = document.querySelector('#medicine-scanner-modal');
const medicineCamera = document.querySelector('#medicine-camera');
const medicinePreview = document.querySelector('#medicine-preview');
const medicineScanStatus = document.querySelector('#medicine-scan-status');
const startMedicineCameraButton = document.querySelector('#start-medicine-camera');
const captureMedicineImageButton = document.querySelector('#capture-medicine-image');
const medicineInfoDisplay = document.querySelector('#medicine-info-display');
const medicineInfoName = document.querySelector('#medicine-info-name');
const medicineInfoContents = document.querySelector('#medicine-info-contents');
const medicineInfoUse = document.querySelector('#medicine-info-use');
const medicineInfoDetails = document.querySelector('#medicine-info-details');
let medicineStream = null;
let barcodeLoopActive = false;

function clearMedicineInfo() { if (medicineInfoDisplay) medicineInfoDisplay.hidden = true; }
async function fetchMedicineInfo(query, byName = false) { if (!db) { setMedicineScanStatus('Database not connected.'); return; } setMedicineScanStatus(`Searching database...`); let data, error; try { if (byName) { ({ data, error } = await db.from('Medicine Data').select('*').ilike('name', `%${query}%`).limit(1).single()); } else { ({ data, error } = await db.from('Medicine Data').select('*').eq('barcode', query).single()); } if (data) { medicineInfoName.textContent = data.name; medicineInfoContents.textContent = data.contents; medicineInfoUse.textContent = data.why_to_use; medicineInfoDetails.textContent = data.info; medicineInfoDisplay.hidden = false; setMedicineScanStatus(`Medicine found: ${data.name}`); } else { medicineInfoDisplay.hidden = true; setMedicineScanStatus(`Medicine not found in database.`); } } catch (e) { medicineInfoDisplay.hidden = true; setMedicineScanStatus(`Medicine not found.`); } }

function setMedicineScanStatus(message, error = false) { medicineScanStatus.textContent = message; medicineScanStatus.classList.toggle('error', error); }
function stopMedicineCamera() { barcodeLoopActive = false; medicineStream?.getTracks().forEach(track => track.stop()); medicineStream = null; if (medicineCamera) medicineCamera.srcObject = null; }
async function detectMedicineBarcode() { if (!barcodeLoopActive || !window.BarcodeDetector || !medicineCamera?.videoWidth) return; try { const detector = new window.BarcodeDetector({ formats: ['ean_13', 'ean_8', 'code_128', 'upc_a', 'upc_e'] }); const codes = await detector.detect(medicineCamera); if (codes[0]?.rawValue) { barcodeLoopActive = false; captureMedicineImageButton.disabled = false; await fetchMedicineInfo(codes[0].rawValue); return; } } catch { /* Camera capture remains available when barcode detection is unavailable. */ } requestAnimationFrame(detectMedicineBarcode); }
async function startMedicineCamera() { clearMedicineInfo(); stopMedicineCamera(); medicinePreview.hidden = true; medicineCamera.hidden = false; captureMedicineImageButton.disabled = true; if (!navigator.mediaDevices?.getUserMedia) { setMedicineScanStatus('Camera access is not available here. Choose a label photo instead.', true); return; } try { setMedicineScanStatus('Opening your rear camera…'); medicineStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); medicineCamera.srcObject = medicineStream; await medicineCamera.play(); captureMedicineImageButton.disabled = false; barcodeLoopActive = true; setMedicineScanStatus(window.BarcodeDetector ? 'Scanning for a barcode…' : 'Camera ready. Capture a clear image of the label.'); requestAnimationFrame(detectMedicineBarcode); } catch { setMedicineScanStatus('Camera permission was not granted. Choose a label photo instead.', true); } }
function captureMedicineImage() { if (!medicineCamera.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = medicineCamera.videoWidth; canvas.height = medicineCamera.videoHeight; canvas.getContext('2d').drawImage(medicineCamera, 0, 0); medicinePreview.src = canvas.toDataURL('image/jpeg', .9); medicinePreview.hidden = false; medicineCamera.hidden = true; stopMedicineCamera(); setMedicineScanStatus('Label captured. Review the image, then use it when you speak with a pharmacist.'); }
async function openMedicineScanner() { openModal('#medicine-scanner-modal'); medicinePreview.hidden = true; medicineCamera.hidden = false; await startMedicineCamera(); }
document.querySelector('#open-medicine-scanner')?.addEventListener('click', event => { event.stopPropagation(); openMedicineScanner(); });
document.querySelector('.hospital-action')?.addEventListener('click', event => { event.stopPropagation(); document.querySelector('#nearby-care').scrollIntoView({ behavior: 'smooth' }); });
startMedicineCameraButton?.addEventListener('click', startMedicineCamera);
captureMedicineImageButton?.addEventListener('click', captureMedicineImage);
document.querySelector('#medicine-file-input')?.addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; stopMedicineCamera(); clearMedicineInfo(); medicinePreview.src = URL.createObjectURL(file); medicinePreview.hidden = false; medicineCamera.hidden = true; captureMedicineImageButton.disabled = false; setMedicineScanStatus('Label image selected. Analyzing text...'); if (file.type.startsWith('image/') && window.TextDetector) { try { const image = await createImageBitmap(file); const blocks = await new window.TextDetector().detect(image); const text = blocks.map(block => block.rawValue).filter(Boolean).join(' '); const words = text.split(/\s+/).filter(w => w.length > 3); if (words.length > 0) { await fetchMedicineInfo(words[0], true); return; } } catch (e) { /* ignore */ } } setMedicineScanStatus('Label image selected. Keep it handy for your pharmacist.'); });
medicineScannerModal?.addEventListener('click', event => { if (event.target === medicineScannerModal || event.target.closest('[data-close-modal]')) stopMedicineCamera(); });

const campList = document.querySelector('#camp-list');
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
async function openBloodCamps() { openModal('#blood-camps-modal'); if (!db) { campList.innerHTML = '<p class="form-status error">Camp details are temporarily unavailable.</p>'; return; } const { data, error } = await db.from('blood_donation_camps').select('title,venue,area,camp_date,start_time,end_time,organizer,status,details,latitude,longitude').order('camp_date', { ascending: false }); if (error || !data?.length) { campList.innerHTML = '<p class="form-status">No verified camp details are available right now. Check the official schedule.</p>'; return; } campList.innerHTML = data.map(camp => `<article class="camp-item ${escapeHtml(camp.status)}"><b>${escapeHtml(camp.title)}</b><small>${escapeHtml(camp.venue)} · ${escapeHtml(camp.area)}<br>${escapeHtml(camp.camp_date)}${camp.start_time ? ` · ${escapeHtml(camp.start_time.slice(0, 5))}${camp.end_time ? `–${escapeHtml(camp.end_time.slice(0, 5))}` : ''}` : ''}<br>${escapeHtml(camp.organizer)}<br>${escapeHtml(camp.details)}</small><span class="camp-status">${escapeHtml(camp.status)}</span></article>`).join(''); }
document.querySelector('.blood-action')?.addEventListener('click', event => { event.stopPropagation(); openBloodCamps(); });

const prescriptionFileInput = document.querySelector('#prescription-file-input');
const prescriptionFileChip = document.querySelector('#prescription-file-chip');
const prescriptionFileName = prescriptionFileChip?.querySelector('b');
const prescriptionText = document.querySelector('#prescription-text');
const simplifiedPrescription = document.querySelector('#simplified-prescription');
let selectedPrescriptionFile = null;
let uploadedPrescriptionId = null;
function openReportAnalyzer() { openModal('#report-analyzer-modal'); }
function resetPrescriptionFile() { selectedPrescriptionFile = null; uploadedPrescriptionId = null; prescriptionFileInput.value = ''; prescriptionFileChip.hidden = true; }
async function extractReadablePrescriptionText(file) { if (!file.type.startsWith('image/') || !window.TextDetector) return; try { const image = await createImageBitmap(file); const blocks = await new window.TextDetector().detect(image); const text = blocks.map(block => block.rawValue).filter(Boolean).join('\n'); if (text) { prescriptionText.value = text; simplifiedPrescription.hidden = false; simplifiedPrescription.textContent = 'Readable text was detected from the image. Review every line carefully before creating a reminder — unclear handwriting must be confirmed with a clinician.'; } } catch { /* Manual review remains available when browser text detection is unavailable. */ } }
prescriptionFileInput?.addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 6291456 || !['image/jpeg', 'image/png', 'application/pdf'].includes(file.type)) { resetPrescriptionFile(); formMessage(document.querySelector('#reminder-status'), 'Choose a JPG, PNG, or PDF smaller than 6 MB.', true); return; } selectedPrescriptionFile = file; uploadedPrescriptionId = null; prescriptionFileName.textContent = file.name; prescriptionFileChip.hidden = false; formMessage(document.querySelector('#reminder-status'), file.type.startsWith('image/') && window.TextDetector ? 'Looking for readable printed text…' : 'File attached. Type only the details you can clearly verify.'); await extractReadablePrescriptionText(file); });
document.querySelector('#remove-prescription-file')?.addEventListener('click', resetPrescriptionFile);
document.querySelector('#simplify-prescription')?.addEventListener('click', () => { const lines = prescriptionText.value.split(/\n|,/).map(line => line.trim()).filter(Boolean); if (!lines.length) { simplifiedPrescription.hidden = false; simplifiedPrescription.textContent = 'Add only the medicine details you can clearly read, then verify them with your doctor or pharmacist.'; return; } simplifiedPrescription.hidden = false; simplifiedPrescription.textContent = `Review each item before use:\n${lines.map((line, index) => `${index + 1}. ${line}`).join('\n')}\n\nNo dose, interaction, or diagnosis has been inferred.`; });
async function storePrescriptionFile(user) { if (!selectedPrescriptionFile || uploadedPrescriptionId) return uploadedPrescriptionId; const safeName = selectedPrescriptionFile.name.replace(/[^a-zA-Z0-9._-]/g, '-'); const path = `${user.id}/${crypto.randomUUID()}-${safeName}`; const { error: uploadError } = await db.storage.from('prescriptions').upload(path, selectedPrescriptionFile, { contentType: selectedPrescriptionFile.type, upsert: false }); if (uploadError) throw uploadError; const { data, error } = await db.from('prescription_uploads').insert({ user_id: user.id, file_path: path, file_name: selectedPrescriptionFile.name, extracted_text: prescriptionText.value.trim() || null }).select('id').single(); if (error) throw error; uploadedPrescriptionId = data.id; return uploadedPrescriptionId; }
document.querySelector('#medicine-reminder-form')?.addEventListener('submit', async event => { event.preventDefault(); const status = document.querySelector('#reminder-status'); if (!db) return formMessage(status, 'The reminder service is being connected. Please try again shortly.', true); const { data: { user } } = await db.auth.getUser(); if (!user) { formMessage(status, 'Please log in before securely saving a prescription or reminder.', true); return; } const form = new FormData(event.currentTarget); try { formMessage(status, 'Saving your verified reminder…'); const prescriptionId = await storePrescriptionFile(user); const { error } = await db.from('medicine_reminders').insert({ user_id: user.id, prescription_upload_id: prescriptionId, medicine_name: form.get('medicine_name'), dosage: form.get('dosage'), reminder_time: form.get('reminder_time'), notes: form.get('notes') || null }); if (error) throw error; formMessage(status, 'Reminder saved. Please keep following your clinician’s instructions.'); if ('Notification' in window && Notification.permission === 'default') Notification.requestPermission(); if ('Notification' in window && Notification.permission === 'granted') new Notification('SCANPHARMA reminder saved', { body: `${form.get('medicine_name')} at ${form.get('reminder_time')}` }); event.currentTarget.reset(); } catch (error) { formMessage(status, error.message || 'We could not save this reminder. Please try again.', true); } });
document.querySelector('.report-action')?.addEventListener('click', event => { event.stopPropagation(); openReportAnalyzer(); });
